### ISSUE TITLE
Error linking local package with latest angular CLI (angular v5+)

### ISSUE THREAD

**Issue by Hughp135** [msarsha/ng2-right-click-menu#51]
Have followed the setting up instructions, but am getting this error from angular CLI. Anyone have any idea how to fix this? (using angular 5.0.1).

This is after doing npm link in the /dist folder of ng2-right-click-menu. Have also added the path to the tsconfig.json etc.

```
WARNING in ./node_modules/ng2-right-click-menu/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.js
71:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\me\git\project\front-end\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\me\git\project\front-end\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\me\git\project\front-end\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\me\git\project\front-end\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Users\me\git\project\front-end\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\me\git\project\front-end\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\me\git\project\front-end\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ng2-right-click-menu/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ./node_modules/ng2-right-click-menu/node_modules/@angular/core/src/linker.js
 @ ./node_modules/ng2-right-click-menu/node_modules/@angular/core/src/core.js
 @ ./node_modules/ng2-right-click-menu/node_modules/@angular/core/index.js
 @ ./node_modules/ng2-right-click-menu/src/sh-context-menu.module.js
 @ ./node_modules/ng2-right-click-menu/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by AlexLnz** [comment]
I can imagine that you have to update Webpack also. Did you check the breaking changes of Angular 5?

**Comment by Hughp135** [comment]
I've been able to reproduce this on a fresh install of angular 5 (latest cli) and fresh clone of the module. This has happened on both my windows and mac machines.

I've made some steps to reproduce in case anyone would have the time to confirm:

```
  npm install -g @angular-cli
  ng new angtest
  git clone https://github.com/msarsha/ng2-right-click-menu.git
  cd ng2-right-click-menu
  npm install
  npm run build
  npm link
  cd ../../angtest
  npm link ng2-right-click-menu
  ng serve
```

Then add the module to the app.module.ts

```
import { ShContextMenuModule } from 'ng2-right-click-menu';
// ....
imports: [
    BrowserModule,
    ShContextMenuModule
  ],
```

Full errors: 
```
WARNING in ../ng2-right-click-menu/dist/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.js
71:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\Users\Hugh\git\angtest\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ../ng2-right-click-menu/dist/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ../ng2-right-click-menu/dist/node_modules/@angular/core/src/linker.js
 @ ../ng2-right-click-menu/dist/node_modules/@angular/core/src/core.js
 @ ../ng2-right-click-menu/dist/node_modules/@angular/core/index.js
 @ ../ng2-right-click-menu/dist/src/sh-context-menu.module.js
 @ ../ng2-right-click-menu/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ../ng2-right-click-menu/dist/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.js
87:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\Users\Hugh\git\angtest\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\Hugh\git\angtest\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ../ng2-right-click-menu/dist/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ../ng2-right-click-menu/dist/node_modules/@angular/core/src/linker.js
 @ ../ng2-right-click-menu/dist/node_modules/@angular/core/src/core.js
 @ ../ng2-right-click-menu/dist/node_modules/@angular/core/index.js
 @ ../ng2-right-click-menu/dist/src/sh-context-menu.module.js
 @ ../ng2-right-click-menu/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by AlexLnz** [comment]
I've repeated the steps, changed only 

    cd ../../angtest

to

    cd ../angtest

I don't get your warnings, but some others:

    WARNING in ../ng2-right-click-menu/src/sh-context-menu.directive.ts
    97:55-72 "export 'IShContextOptions' was not found in './sh-context-menu.models'

    WARNING in ../ng2-right-click-menu/src/sh-context-menu.directive.ts
    97:92-109 "export 'IShContextOptions' was not found in './sh-context-menu.models'

**Comment by Hughp135** [comment]
Forgot to add a line to cd to dist in ng2-right-click-menu before linking (as the js compiled package is built inside the dist folder the way the project is setup).

**Comment by Hughp135** [comment]
Well, I have no idea how, but I got it to work temporarily after fiddling around for hours with stuff with `ng serve --preserve-symlinks`. 

I then tried to reproduce on a new copy and it now doesn't work again, at all, even with the same code. So I'm thinking it might be a bug unrelated to this repo...

**Comment by roopkt** [comment]
Hi @Hughp135 
Did you try this with Angular 4 project is npm link working over there? 
I created one issue in angular cli https://github.com/angular/angular-cli/issues/9273

**Comment by Hughp135** [comment]
Nah I haven't @roopkt  - not sure which version of angular CLI I need to use for angular 4 (had a quick look through the release notes but couldn't find any specific angular version)

**Comment by msarsha** [comment]
Hey guys!

I just pushed a new branch using ng-packagr [ng-packagr branch](https://github.com/msarsha/ng2-right-click-menu/tree/ng-packagr)

This should remove the need to symlink and also make the development process more fluid.

I also added angular-cli to the project:

````
npm install
npm start // to run the demo application
````

Keep developing under `./lib` and the application will refresh on changes.

Will be awesome if you could clone it and test on your machines everything is working - so I could merge it the the master branch.

**Comment by Hughp135** [comment]
Have tried your branch and everything works smoothly :)

**Comment by msarsha** [comment]
Awesome, I also gave it a try on a clean machine.

Will merge it tomorrow.

**Comment by Hughp135** [comment]
Also `npm link` worked to link the built project. However it seems to still have compatibility issues with my Angular 5 project. (this error)

![screen shot 2018-01-09 at 14 57 13](https://user-images.githubusercontent.com/12624925/34726975-6c784c16-f54d-11e7-8820-eac9869f94f8.png)

Not sure if this would effect the next release of the project on npm or if it's only an issue with developing locally.

**Comment by msarsha** [comment]
Weird. You get that error when linking the `lib-build` folder?

**Comment by Hughp135** [comment]
Yeah

**Comment by msarsha** [comment]
@Hughp135 

I assume what you are trying to do it test that the library works after building.

If that is the case, cd to `lib-build` and run `npm pack` which will generate a `.tgz` file.

Now, in your application install the built library using `npm install --save <path to .tgz file>`
